name: Check if we should add/remove association with PR from Repo2

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - closed

jobs:
  associate-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo1 PR number and title
        id: get_number_and_title

        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_OUTPUT

      - name: Check for reference to another PR from Repo2
        run: |
          PR_NUMBER="${{ steps.get_number_and_title.outputs.PR_NUMBER }}"
          PR_TITLE="${{ steps.get_number_and_title.outputs.PR_TITLE }}"
          # Check if the title contains the pattern for another repo's PR
          if [[ "$PR_TITLE" =~ \[Repo\ B\ ([0-9]+)\] ]]; then
            SUBMODULE_PR_NUMBER="${BASH_REMATCH[1]}"
            echo "SUBMODULE_PR_NUMBER=$SUBMODULE_PR_NUMBER" >> $GITHUB_OUTPUT
            echo "Referenced PR #$SUBMODULE_PR_NUMBER found" 
          else
            echo "No referenced PR found in title"
            exit 0
          fi