name: Sync merge

on:
  pull_request:
    types: [closed]

jobs:
  try-to-merge-in-submodule-repo:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run a script
      run: echo "Repo1 PR has been merged"

    - name: Extract PR number from description
      id: extract-pr
      run: |
        # Get PR description
        PR_DESCRIPTION=$(echo "${{ github.event.pull_request.body }}" | tr '[:upper:]' '[:lower:]')
        # Extract URL using grep and regex
        if [[ $PR_DESCRIPTION =~ related[[:space:]]repo2[[:space:]]pr:[[:space:]](https://github.com/mateuuszzzzz/repo2/pull/)?([0-9]+) ]]; then
          PR_NUMBER="${BASH_REMATCH[2]}"
          echo "Found PR number: $PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        else
          echo "Error: Could not find related PR URL in the description"
          exit 1
        fi

    - name: Merge PR in target repository
      run: |
        curl -L --fail \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MERGE_PAT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/mateuuszzzzz/repo2/pulls/${{ steps.extract-pr.outputs.pr_number }}/merge \
          -d '{"merge_method":"squash"}'
  bump-submodule-commit:
    needs: try-to-merge-in-submodule-repo
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        submodules: true
        token: ${{ secrets.COMMIT_PAT_TOKEN }}
      
    - name: Bump submodule commit
      run: |
        git submodule update --init
        cd Repo2
        git checkout main
        git pull origin main
        cd ..
        git add Repo2
        git commit -m "Update Repo2 commit after merge of ${{ github.event.pull_request.number }}"
        
        